# Generated by Django 3.2.5 on 2021-07-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='time',
            new_name='date',
        ),
    ]
